### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by sydneyabuya** [SydneySmoothvile/rental_housing#9]
I would encourage you to clone again ,juu nimechange hizo branches. 
Then git checkout to team, that is the branch tutatumia.
Then you work on the Tenant Dashboard .
Weka hio payment hapo ,ama kwa resources/views/frontend/invoice/invoice.blade.php

**Comment by sydneyabuya** [comment]
After Cloning
Run **cp .env.example .env** file to copy example file to .env
Then edit your .env file with DB credentials and other settings.
Run **composer install** command
Run **php artisan migrate --seed** command.
Notice: seed is important, because it will create the first admin user for you.
Run **php artisan key:generate** command.


Username: admin@admin.com
Password: password

**Comment by Not-Caleb** [comment]
Thanks.I had forgot some of the commands
